### ISSUE TITLE
WSSecurityCert: this.security.toXML is not a function after upgrading to 1.6.4

### ISSUE THREAD

**Issue by logslie** [vpulim/node-soap#1434]
After upgrading from soap@1.1.11 to soap@1.6.4, using WSSecurityCert throws the error: **this.security.toXML is not a function**                                                                                                                                                             
                                                                                                                                                                                                    
  Environment:                                                                                                                                                                                      
  - soap version: 1.6.4                                                                                                                                                                             
  - Node.js version: 22.x                                                                                                                                                                           
  - OS: Linux (also reproducible on macOS)     

Steps to reproduce:                                                                                                                                                                               
                                                                                                                                                                                                    
```
  import * as soap from "soap";                                                                                                                                                                     
                                                                                                                                                                                                    
  const client = await soap.createClientAsync(wsdlUrl);                                                                                                                                             
                                                                                                                                                                                                    
  const security = new soap.WSSecurityCert(privateKey, publicCert, password, {                                                                                                                      
    hasTimeStamp: true,                                                                                                                                                                             
    signatureAlgorithm: "http://www.w3.org/2000/09/xmldsig#rsa-sha1",                                                                                                                               
    digestAlgorithm: "http://www.w3.org/2000/09/xmldsig#sha1",                                                                                                                                      
    signatureTransformations: ["http://www.w3.org/2001/10/xml-exc-c14n#"],                                                                                                                          
  });                                                                                                                                                                                               
                                                                                                                                                                                                    
  client.setSecurity(security);                                                                                                                                                                     
                                                                                                                                                                                                    
  // Any SOAP method call triggers the error                                                                                                                                                        
  await client.SomeMethodAsync(params);     
```                                                                                                                                                        
 The SOAP request should be signed with WS-Security and sent successfully (works in 1.1.11), but it throws `TypeError: this.security.toXML is not a function.`                                                                                                                                           
 Looking at the ISecurity interface, toXML() is documented as "not executed if postProcess is also defined." It appears that WSSecurityCert in 1.6.4 implements postProcess() instead of toXML(), but there's code internally that still calls toXML() directly, causing this error.

**Comment by smokhov** [comment]
Duplicate of #1422 ... @w666 -- we can either update README with the example to use `ClientSSLSecurity` (like the tests do) instead of `WSSecurityCert`, or provide a dummy `toXML()` to all *`Cert()` classes, similar how to other `ISecurity` implementations do.

@logslie -- please use `ClientSSLSecurity` for now instead of  `WSSecurityCert`

**Comment by w666** [comment]
@smokhov, I feel like we should do both, update docs and provide dummy `toXML`.

**Comment by w666** [comment]
@logslie 

here is very simple workaround, could you please test this in your code?

https://github.com/vpulim/node-soap/pull/1435

**Comment by adammolnar** [comment]
I still get an error using `WSSecurityCert`. To fix this, `src/client.ts` should be changed.
expression must be truthy:
```
if (this.security && typeof this.security?.toXML !== 'function') {
  security.toXML = () => ' ';
}
```
See https://github.com/vpulim/node-soap/commit/d83307dc9d3b571e4db8d552cb51aade57028481#r180655305

**Comment by w666** [comment]
Hi @adammolnar, do you mind creating a PR?
