### ISSUE TITLE
Cannot run with jest since version 1.6.5

### ISSUE THREAD

**Issue by ThHareau** [vpulim/node-soap#1446]
Hi, 

Since version 1.6.5, I cannot make jest + ts-jest work. The issue might be a jest configuration, but I cannot figure what is missing by myself. 

I have the following error: 

```
    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation, specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    .../node_modules/get-stream/source/index.js:1
    import {on} from 'node:events';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

This is most probably linked to get-stream upgrade.

To reproduce, I created a new npm folder, with jest, ts-jest, soap and the following test file: 

```
import * as soap from 'soap';

export const create = () => soap.createClientAsync('https://localhost:8080').then(console.log)
```

Any idea on how to solve this?

**Comment by calvin-cdev** [comment]
having the same issue
soap 1.6.5
jest 29.7.0
node 24.12.0

**Comment by w666** [comment]
Hi @ThHareau,

What are your node.js, jest and ts-jest versions?

Thanks.

**Comment by w666** [comment]
I've replicated this issue, seems like caused by `get-stream` dependency. It was not picked up by tests because tests use commonjs style imports. 

I will create a test for this and very likely will revert that dependency update.

**Comment by w666** [comment]
@ThHareau  @calvin-cdev 

Here is a PR where I just replaced get-stream, should work now, if you can help to test this in your env that would really help.

Thanks.

**Comment by ThHareau** [comment]
@w666

Thank you for your help 🙂 

 I'm now having the same issue with strip-bom : 

```
    .../node_modules/strip-bom/index.js:1
    export default function stripBom(string) {
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      12 | import * as path from 'path';
      13 | import * as sax from 'sax';
    > 14 | import stripBom from 'strip-bom';
```

It may be worth to replace it as well? The library seems to be very short

**Comment by w666** [comment]
@ThHareau 

Done, replaced strip-bom as well. Passed my local testing, but still would be good to double check on your side. Thanks.

**Comment by RettentoRectangle** [comment]
Same here:

    /node_modules/soap/node_modules/get-stream/source/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import {on} from 'node:events';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 13 | import { WSDL } from 'soap'

node: v24.3.0
jest: v29.7.0
ts-jest: v29.4.2
soap: 1.6.5

Thanks for fix!

**Comment by w666** [comment]
version 1.7.0 has been released. Please let me know if you still have any issues with it. Sorry for the bad previous release.

**Comment by ThHareau** [comment]
Thank you for maintaining this 🙂 

Sadly there is still an issue I believe, the compiled code still contains a reference to get-stream: 

```
Cannot find module 'get-stream' from 'node_modules/soap/lib/client.js'
```

And when I look at the compiled js code, in client.js line 48: 

```
const get_stream_1 = __importDefault(require("get-stream"));
```

~~I can reopen an issue if you whish~~  done by someone else: https://github.com/vpulim/node-soap/issues/1448

**Comment by w666** [comment]
@ThHareau 

Just released 1.7.1, this was a bit unfortunate, was working on two different machines for this release.

**Comment by SherpaMiguel** [comment]
Thank you so much guys, especially @w666 !

**Comment by RettentoRectangle** [comment]
@w666 
It's working, thanks!

**Comment by danielrentz** [comment]
@w666 JFYI, as I stumbled over this issue by accident. We had similar problems with a few external packages in out tests, and we are using Jest's "transformIgnorePatterns" option to tell Jest to transform these package from ESM to CJS (just in case this happens again with a heavier package).

For example:

```js
    transformIgnorePatterns: [
        "/node_modules/(?!(get-stream|strip-bom)/)",
    ],
```

This tells Jest to ignore all code in node_modules _except_ the listed packages. [Default value for this option](https://jestjs.io/docs/configuration#transformignorepatterns-arraystring) contains `"/node_modules/"` to skip transforming all external packages.
