### ISSUE TITLE
TypeError: (0 , crypto_1.randomUUID) is not a function

### ISSUE THREAD

**Issue by TarasKomaryshyn** [vpulim/node-soap#1266]
I use soap 1.1.5 version. My node version is 14.16.1 where "crypto.randomUUID" function is not added yet (see https://nodejs.org/api/crypto.html#cryptorandomuuidoptions). In soap 1.1.5 version "engines.node" says ">=14.0.0" which seems to be wrong since "crypto.randomUUID" added for the first time in node  v14.17.0

crypto.randomUUID" used in '/soap/lib/client.js' line 367(): 
`const eid = options.exchangeId || (0, crypto_1.randomUUID)();`

package.json:
`"name": "soap",
  "version": "1.1.5",
  "engines": {
    "node": ">=14.0.0"
  },`
  
  
  I believe this issue is present in the latest version as well.

**Comment by w666** [comment]
Hi @TarasKomaryshyn 

Sorry for the wrong info about minimal node version.
It was major work in version `1.1.0` to fix all the security issues and remove unwanted dependencies.
I am happy to update `package.json` to the correct node version. 

Would you be able to upgrade your node to 14.17.0?

**Comment by TarasKomaryshyn** [comment]
Hi @w666,

Yes, I think it'll be the best solution. 

Thanks.
