### PR TITLE
Bug where no prototypical inheritence chain exists

### PR DESCRIPTION
**Pull request by NoMan2000**
- Some transpilers will create objects using `Object.create(null)`.  This creates an object with no prototypical inheritance, so there is no `hasOwnProperty` method on it.

The fix is if that if such an object exists, use `Object.assign` to copy the prototype chain from an empty object into the null created obj.

Otherwise, you just get a TypeError that `obj.hasOwnProperty is not a function`.

Signed-off-by: NoMan2000 <webart.video@gmail.com>

### CODE REVIEW

**Comment by ZacharyKearns** [comment]
Is anyone reviewing this? After updating to v0.31.0 this issue broke my app I had to roll back to a previous version.

**Comment by NoMan2000** [comment]
The fix is dead simple, so I'm guessing that they haven't seen it?

**Comment by ZacharyKearns** [comment]
This didn't fix my issue unfortunately. Any null values in the args still causes the request to fail.

**Comment by NoMan2000** [comment]
> This didn't fix my issue unfortunately. Any null values in the args still causes the request to fail.

Can you submit some sample code and tag me on it?
